GRANULARITY_LIST = [
    "1 Minute",
    "2 Minutes",
    "5 Minutes",
    "15 Minutes",
    "30 Minutes",
    "60 Minutes",
    "90 Minutes",
    "1 Hour",
    "1 Day",
    "5 Days",
    "1 Week",
    "1 Month",
    "3 Months",
]

GRANULARITY_DICT = {
    "1 Day": "1d",
    "1 Minute": "1m",
    "2 Minutes": "2m",
    "5 Minutes": "5m",
    "15 Minutes": "15m",
    "30 Minutes": "30m",
    "60 Minutes": "60m",
    "90 Minutes": "90m",
    "1 Hour": "1h",
    "5 Days": "5d",
    "1 Week": "1wk",
    "1 Month": "1mo",
    "3 Months": "3mo",
}

YFINANCE_TICKER_INFO_KEYS = [
    "address1",
    "city",
    "state",
    "zip",
    "country",
    "phone",
    "website",
    "industry",
    "industryKey",
    "industryDisp",
    "sector",
    "sectorKey",
    "sectorDisp",
    "longBusinessSummary",
    "fullTimeEmployees",
    "companyOfficers",
    "auditRisk",
    "boardRisk",
    "compensationRisk",
    "shareHolderRightsRisk",
    "overallRisk",
    "governanceEpochDate",
    "compensationAsOfEpochDate",
    "irWebsite",
    "executiveTeam",
    "maxAge",
    "priceHint",
    "previousClose",
    "open",
    "dayLow",
    "dayHigh",
    "regularMarketPreviousClose",
    "regularMarketOpen",
    "regularMarketDayLow",
    "regularMarketDayHigh",
    "exDividendDate",
    "payoutRatio",
    "fiveYearAvgDividendYield",
    "beta",
    "forwardPE",
    "volume",
    "regularMarketVolume",
    "averageVolume",
    "averageVolume10days",
    "averageDailyVolume10Day",
    "bid",
    "ask",
    "bidSize",
    "askSize",
    "marketCap",
    "fiftyTwoWeekLow",
    "fiftyTwoWeekHigh",
    "allTimeHigh",
    "allTimeLow",
    "priceToSalesTrailing12Months",
    "fiftyDayAverage",
    "twoHundredDayAverage",
    "trailingAnnualDividendRate",
    "trailingAnnualDividendYield",
    "currency",
    "tradeable",
    "enterpriseValue",
    "profitMargins",
    "floatShares",
    "sharesOutstanding",
    "sharesShort",
    "sharesShortPriorMonth",
    "sharesShortPreviousMonthDate",
    "dateShortInterest",
    "sharesPercentSharesOut",
    "heldPercentInsiders",
    "heldPercentInstitutions",
    "shortRatio",
    "shortPercentOfFloat",
    "impliedSharesOutstanding",
    "bookValue",
    "lastFiscalYearEnd",
    "nextFiscalYearEnd",
    "mostRecentQuarter",
    "netIncomeToCommon",
    "trailingEps",
    "forwardEps",
    "lastSplitFactor",
    "lastSplitDate",
    "enterpriseToRevenue",
    "enterpriseToEbitda",
    "52WeekChange",
    "SandP52WeekChange",
    "lastDividendValue",
    "lastDividendDate",
    "quoteType",
    "currentPrice",
    "targetHighPrice",
    "targetLowPrice",
    "targetMeanPrice",
    "targetMedianPrice",
    "recommendationMean",
    "recommendationKey",
    "numberOfAnalystOpinions",
    "totalCash",
    "totalCashPerShare",
    "ebitda",
    "totalDebt",
    "quickRatio",
    "currentRatio",
    "totalRevenue",
    "revenuePerShare",
    "returnOnAssets",
    "grossProfits",
    "freeCashflow",
    "operatingCashflow",
    "revenueGrowth",
    "grossMargins",
    "ebitdaMargins",
    "operatingMargins",
    "financialCurrency",
    "symbol",
    "language",
    "region",
    "typeDisp",
    "quoteSourceName",
    "triggerable",
    "customPriceAlertConfidence",
    "exchange",
    "messageBoardId",
    "exchangeTimezoneName",
    "exchangeTimezoneShortName",
    "gmtOffSetMilliseconds",
    "market",
    "esgPopulated",
    "corporateActions",
    "regularMarketTime",
    "marketState",
    "shortName",
    "longName",
    "hasPrePostMarketData",
    "firstTradeDateMilliseconds",
    "regularMarketChangePercent",
    "regularMarketPrice",
    "regularMarketChange",
    "regularMarketDayRange",
    "fullExchangeName",
    "averageDailyVolume3Month",
    "fiftyTwoWeekLowChange",
    "fiftyTwoWeekLowChangePercent",
    "fiftyTwoWeekRange",
    "fiftyTwoWeekHighChange",
    "fiftyTwoWeekHighChangePercent",
    "fiftyTwoWeekChangePercent",
    "dividendDate",
    "earningsTimestamp",
    "earningsTimestampStart",
    "earningsTimestampEnd",
    "earningsCallTimestampStart",
    "earningsCallTimestampEnd",
    "isEarningsDateEstimate",
    "epsTrailingTwelveMonths",
    "epsForward",
    "epsCurrentYear",
    "priceEpsCurrentYear",
    "fiftyDayAverageChange",
    "fiftyDayAverageChangePercent",
    "twoHundredDayAverageChange",
    "twoHundredDayAverageChangePercent",
    "priceToBook",
    "sourceInterval",
    "exchangeDataDelayedBy",
    "averageAnalystRating",
    "cryptoTradeable",
    "trailingPegRatio",
]
